//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StrygevaleDatabase.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Journal
    {
        public int id_journal { get; set; }
        public int id_lesson { get; set; }
        public string grade { get; set; }
        public int id_student { get; set; }
    
        public virtual Lesson Lesson { get; set; }
        public virtual Student Student { get; set; }
    }
}
